# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/royalstate/Projects and Research/Python Projects/Audio-Metadata-Editor/utils/Design_Files/download_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_downloadForm(object):
    def setupUi(self, downloadForm):
        downloadForm.setObjectName("downloadForm")
        downloadForm.resize(500, 200)
        downloadForm.setMinimumSize(QtCore.QSize(0, 200))
        downloadForm.setMaximumSize(QtCore.QSize(500, 600))
        self.textBrowser = QtWidgets.QTextBrowser(downloadForm)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 500, 62))
        self.textBrowser.setMaximumSize(QtCore.QSize(500, 62))
        self.textBrowser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textBrowser.setReadOnly(True)
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(downloadForm)
        self.label.setGeometry(QtCore.QRect(10, 80, 50, 20))
        self.label.setMinimumSize(QtCore.QSize(50, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.urlEntry = QtWidgets.QLineEdit(downloadForm)
        self.urlEntry.setGeometry(QtCore.QRect(70, 80, 420, 21))
        self.urlEntry.setMinimumSize(QtCore.QSize(420, 21))
        self.urlEntry.setMaximumSize(QtCore.QSize(16777215, 21))
        self.urlEntry.setObjectName("urlEntry")
        self.line = QtWidgets.QFrame(downloadForm)
        self.line.setGeometry(QtCore.QRect(10, 100, 481, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.viewLogsButton = QtWidgets.QPushButton(downloadForm)
        self.viewLogsButton.setGeometry(QtCore.QRect(420, 170, 75, 23))
        self.viewLogsButton.setMinimumSize(QtCore.QSize(0, 23))
        self.viewLogsButton.setMaximumSize(QtCore.QSize(16777215, 23))
        self.viewLogsButton.setCheckable(True)
        self.viewLogsButton.setObjectName("viewLogsButton")
        self.downloadButton = QtWidgets.QPushButton(downloadForm)
        self.downloadButton.setGeometry(QtCore.QRect(120, 170, 111, 23))
        self.downloadButton.setMinimumSize(QtCore.QSize(0, 23))
        self.downloadButton.setMaximumSize(QtCore.QSize(16777215, 23))
        self.downloadButton.setDefault(True)
        self.downloadButton.setObjectName("downloadButton")
        self.line_2 = QtWidgets.QFrame(downloadForm)
        self.line_2.setGeometry(QtCore.QRect(10, 150, 481, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.typeComboBox = QtWidgets.QComboBox(downloadForm)
        self.typeComboBox.setGeometry(QtCore.QRect(60, 120, 70, 22))
        self.typeComboBox.setMinimumSize(QtCore.QSize(70, 22))
        self.typeComboBox.setMaximumSize(QtCore.QSize(70, 22))
        self.typeComboBox.setObjectName("typeComboBox")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(downloadForm)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 40, 22))
        self.label_2.setMinimumSize(QtCore.QSize(40, 22))
        self.label_2.setMaximumSize(QtCore.QSize(40, 22))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.seeAvailFormatsButton = QtWidgets.QPushButton(downloadForm)
        self.seeAvailFormatsButton.setGeometry(QtCore.QRect(294, 170, 111, 23))
        self.seeAvailFormatsButton.setMinimumSize(QtCore.QSize(100, 23))
        self.seeAvailFormatsButton.setMaximumSize(QtCore.QSize(16777215, 23))
        self.seeAvailFormatsButton.setObjectName("seeAvailFormatsButton")
        self.getThumbCheck = QtWidgets.QCheckBox(downloadForm)
        self.getThumbCheck.setGeometry(QtCore.QRect(170, 120, 90, 16))
        self.getThumbCheck.setMinimumSize(QtCore.QSize(90, 16))
        self.getThumbCheck.setMaximumSize(QtCore.QSize(16777215, 17))
        self.getThumbCheck.setChecked(True)
        self.getThumbCheck.setObjectName("getThumbCheck")
        self.line_3 = QtWidgets.QFrame(downloadForm)
        self.line_3.setGeometry(QtCore.QRect(140, 120, 20, 30))
        self.line_3.setMaximumSize(QtCore.QSize(20, 30))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.geoBypassCheck = QtWidgets.QCheckBox(downloadForm)
        self.geoBypassCheck.setGeometry(QtCore.QRect(170, 140, 82, 17))
        self.geoBypassCheck.setMinimumSize(QtCore.QSize(82, 17))
        self.geoBypassCheck.setMaximumSize(QtCore.QSize(16777215, 17))
        self.geoBypassCheck.setObjectName("geoBypassCheck")
        self.playlistCheck = QtWidgets.QCheckBox(downloadForm)
        self.playlistCheck.setGeometry(QtCore.QRect(270, 120, 61, 17))
        self.playlistCheck.setMinimumSize(QtCore.QSize(60, 17))
        self.playlistCheck.setMaximumSize(QtCore.QSize(16777215, 17))
        self.playlistCheck.setObjectName("playlistCheck")
        self.setDestButton = QtWidgets.QPushButton(downloadForm)
        self.setDestButton.setGeometry(QtCore.QRect(20, 170, 90, 20))
        self.setDestButton.setMinimumSize(QtCore.QSize(90, 0))
        self.setDestButton.setMaximumSize(QtCore.QSize(25, 20))
        self.setDestButton.setObjectName("setDestButton")
        self.getDescriptionCheck = QtWidgets.QCheckBox(downloadForm)
        self.getDescriptionCheck.setGeometry(QtCore.QRect(260, 140, 92, 17))
        self.getDescriptionCheck.setMinimumSize(QtCore.QSize(92, 17))
        self.getDescriptionCheck.setMaximumSize(QtCore.QSize(16777215, 17))
        self.getDescriptionCheck.setObjectName("getDescriptionCheck")
        self.embedThumbCheck = QtWidgets.QCheckBox(downloadForm)
        self.embedThumbCheck.setGeometry(QtCore.QRect(330, 120, 111, 17))
        self.embedThumbCheck.setMinimumSize(QtCore.QSize(100, 17))
        self.embedThumbCheck.setMaximumSize(QtCore.QSize(16777215, 17))
        self.embedThumbCheck.setObjectName("embedThumbCheck")
        self.writeMetaCheck = QtWidgets.QCheckBox(downloadForm)
        self.writeMetaCheck.setGeometry(QtCore.QRect(360, 140, 101, 17))
        self.writeMetaCheck.setMinimumSize(QtCore.QSize(100, 17))
        self.writeMetaCheck.setMaximumSize(QtCore.QSize(16777215, 17))
        self.writeMetaCheck.setObjectName("writeMetaCheck")
        self.loggingTextEdit = QtWidgets.QTextEdit(downloadForm)
        self.loggingTextEdit.setGeometry(QtCore.QRect(0, 200, 500, 400))
        self.loggingTextEdit.setMaximumSize(QtCore.QSize(500, 400))
        self.loggingTextEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.loggingTextEdit.setReadOnly(True)
        self.loggingTextEdit.setObjectName("loggingTextEdit")
        self.stopButton = QtWidgets.QPushButton(downloadForm)
        self.stopButton.setEnabled(False)
        self.stopButton.setGeometry(QtCore.QRect(240, 170, 35, 20))
        self.stopButton.setMinimumSize(QtCore.QSize(35, 20))
        self.stopButton.setMaximumSize(QtCore.QSize(35, 20))
        self.stopButton.setObjectName("stopButton")

        self.retranslateUi(downloadForm)
        QtCore.QMetaObject.connectSlotsByName(downloadForm)

    def retranslateUi(self, downloadForm):
        _translate = QtCore.QCoreApplication.translate
        downloadForm.setWindowTitle(_translate("downloadForm", "DOWNLOAD A MUSIC FILE"))
        self.textBrowser.setHtml(_translate("downloadForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Download a music file from the Internet.</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You can download files from you YouTube, Facebook, Google-Drive, Instagram and lots more sites. See supported sites <a href=\"https://ytdl-org.github.io/youtube-dl/supportedsites.html\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">here</span></a><a href=\"https://ytdl-org.github.io/youtube-dl/supportedsites.html\"><span style=\" font-size:8pt; text-decoration: underline; color:#000000;\">. Developed by </span></a><a href=\"https://github.com/ayieko168\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">ayieko168</span></a></p></body></html>"))
        self.label.setText(_translate("downloadForm", "URL(s) :"))
        self.urlEntry.setPlaceholderText(_translate("downloadForm", "Example: https://youtu.be/vpk_1gldOAE"))
        self.viewLogsButton.setText(_translate("downloadForm", "View Logs..."))
        self.downloadButton.setText(_translate("downloadForm", "Download"))
        self.typeComboBox.setItemText(0, _translate("downloadForm", "MP3"))
        self.typeComboBox.setItemText(1, _translate("downloadForm", "ACC"))
        self.typeComboBox.setItemText(2, _translate("downloadForm", "BEST"))
        self.typeComboBox.setItemText(3, _translate("downloadForm", "FLAC"))
        self.typeComboBox.setItemText(4, _translate("downloadForm", "M4A"))
        self.typeComboBox.setItemText(5, _translate("downloadForm", "OGG"))
        self.typeComboBox.setItemText(6, _translate("downloadForm", "VORBIS"))
        self.typeComboBox.setItemText(7, _translate("downloadForm", "WAV"))
        self.label_2.setText(_translate("downloadForm", "Type :"))
        self.seeAvailFormatsButton.setText(_translate("downloadForm", "See Avalible Formats"))
        self.getThumbCheck.setText(_translate("downloadForm", "Get Thumbnail"))
        self.geoBypassCheck.setText(_translate("downloadForm", "Geo ByPass"))
        self.playlistCheck.setText(_translate("downloadForm", "Playlist"))
        self.setDestButton.setText(_translate("downloadForm", "Set Destination"))
        self.getDescriptionCheck.setText(_translate("downloadForm", "Get Description"))
        self.embedThumbCheck.setText(_translate("downloadForm", "Embed Thumbnail"))
        self.writeMetaCheck.setText(_translate("downloadForm", "Write Metadata"))
        self.stopButton.setText(_translate("downloadForm", "Stop!"))
