# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/ayieko/Projects And Research/Python Projects/Audio-Metadata-Editor/utils/Design_Files/MainFrontEnd.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(891, 701)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.titleEditSingle = QtWidgets.QLineEdit(self.tab)
        self.titleEditSingle.setMinimumSize(QtCore.QSize(371, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setUnderline(False)
        self.titleEditSingle.setFont(font)
        self.titleEditSingle.setObjectName("titleEditSingle")
        self.verticalLayout.addWidget(self.titleEditSingle)
        self.label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.albumEditSingle = QtWidgets.QLineEdit(self.tab)
        self.albumEditSingle.setMinimumSize(QtCore.QSize(371, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setUnderline(False)
        self.albumEditSingle.setFont(font)
        self.albumEditSingle.setObjectName("albumEditSingle")
        self.verticalLayout.addWidget(self.albumEditSingle)
        self.label_4 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.artistEditSingle = QtWidgets.QLineEdit(self.tab)
        self.artistEditSingle.setMinimumSize(QtCore.QSize(371, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setUnderline(False)
        self.artistEditSingle.setFont(font)
        self.artistEditSingle.setObjectName("artistEditSingle")
        self.verticalLayout.addWidget(self.artistEditSingle)
        self.label_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.contributorsEditSingle = QtWidgets.QLineEdit(self.tab)
        self.contributorsEditSingle.setMinimumSize(QtCore.QSize(371, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setUnderline(False)
        self.contributorsEditSingle.setFont(font)
        self.contributorsEditSingle.setObjectName("contributorsEditSingle")
        self.verticalLayout.addWidget(self.contributorsEditSingle)
        self.label_5 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.GenreEditSingle = QtWidgets.QLineEdit(self.tab)
        self.GenreEditSingle.setMinimumSize(QtCore.QSize(371, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setUnderline(False)
        self.GenreEditSingle.setFont(font)
        self.GenreEditSingle.setObjectName("GenreEditSingle")
        self.verticalLayout.addWidget(self.GenreEditSingle)
        self.label_6 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.composerEditSingle = QtWidgets.QLineEdit(self.tab)
        self.composerEditSingle.setMinimumSize(QtCore.QSize(371, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setUnderline(False)
        self.composerEditSingle.setFont(font)
        self.composerEditSingle.setObjectName("composerEditSingle")
        self.verticalLayout.addWidget(self.composerEditSingle)
        self.label_7 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.compilationEditSingle = QtWidgets.QLineEdit(self.tab)
        self.compilationEditSingle.setMinimumSize(QtCore.QSize(371, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setUnderline(False)
        self.compilationEditSingle.setFont(font)
        self.compilationEditSingle.setObjectName("compilationEditSingle")
        self.verticalLayout.addWidget(self.compilationEditSingle)
        self.label_8 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.commentTextSingle = QtWidgets.QTextEdit(self.tab)
        self.commentTextSingle.setMinimumSize(QtCore.QSize(371, 111))
        self.commentTextSingle.setBaseSize(QtCore.QSize(371, 111))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setUnderline(False)
        self.commentTextSingle.setFont(font)
        self.commentTextSingle.setAcceptRichText(False)
        self.commentTextSingle.setObjectName("commentTextSingle")
        self.verticalLayout.addWidget(self.commentTextSingle)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 7, 1)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 1, 7, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.yearSpinSingle = QtWidgets.QSpinBox(self.tab)
        self.yearSpinSingle.setMaximum(3000)
        self.yearSpinSingle.setProperty("value", 2000)
        self.yearSpinSingle.setObjectName("yearSpinSingle")
        self.horizontalLayout.addWidget(self.yearSpinSingle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.trackNumSpinSingle = QtWidgets.QSpinBox(self.tab)
        self.trackNumSpinSingle.setMaximum(3000)
        self.trackNumSpinSingle.setProperty("value", 1)
        self.trackNumSpinSingle.setObjectName("trackNumSpinSingle")
        self.horizontalLayout_2.addWidget(self.trackNumSpinSingle)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.totalTracksSpinSingle = QtWidgets.QSpinBox(self.tab)
        self.totalTracksSpinSingle.setMaximum(3000)
        self.totalTracksSpinSingle.setProperty("value", 10)
        self.totalTracksSpinSingle.setObjectName("totalTracksSpinSingle")
        self.horizontalLayout_2.addWidget(self.totalTracksSpinSingle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.diskNumSpinSingle = QtWidgets.QSpinBox(self.tab)
        self.diskNumSpinSingle.setMaximum(3000)
        self.diskNumSpinSingle.setProperty("value", 1)
        self.diskNumSpinSingle.setObjectName("diskNumSpinSingle")
        self.horizontalLayout_3.addWidget(self.diskNumSpinSingle)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.totalDiskSpinSingle = QtWidgets.QSpinBox(self.tab)
        self.totalDiskSpinSingle.setMaximum(3000)
        self.totalDiskSpinSingle.setProperty("value", 2)
        self.totalDiskSpinSingle.setObjectName("totalDiskSpinSingle")
        self.horizontalLayout_3.addWidget(self.totalDiskSpinSingle)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(220, 220))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(False)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.artLabelSingle = QtWidgets.QLabel(self.groupBox)
        self.artLabelSingle.setGeometry(QtCore.QRect(10, 20, 200, 200))
        self.artLabelSingle.setFrameShape(QtWidgets.QFrame.Box)
        self.artLabelSingle.setText("")
        self.artLabelSingle.setObjectName("artLabelSingle")
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.findArtButtonSingle = QtWidgets.QPushButton(self.tab)
        self.findArtButtonSingle.setMinimumSize(QtCore.QSize(131, 0))
        self.findArtButtonSingle.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.findArtButtonSingle.setFont(font)
        self.findArtButtonSingle.setObjectName("findArtButtonSingle")
        self.horizontalLayout_4.addWidget(self.findArtButtonSingle)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 4, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.filePathEntrySingle = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setUnderline(False)
        self.filePathEntrySingle.setFont(font)
        self.filePathEntrySingle.setText("")
        self.filePathEntrySingle.setObjectName("filePathEntrySingle")
        self.verticalLayout_2.addWidget(self.filePathEntrySingle)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 5, 2, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.openButtonSingle = QtWidgets.QPushButton(self.tab)
        self.openButtonSingle.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.openButtonSingle.setFont(font)
        self.openButtonSingle.setObjectName("openButtonSingle")
        self.horizontalLayout_5.addWidget(self.openButtonSingle)
        self.saveButtonSingle = QtWidgets.QPushButton(self.tab)
        self.saveButtonSingle.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.saveButtonSingle.setFont(font)
        self.saveButtonSingle.setObjectName("saveButtonSingle")
        self.horizontalLayout_5.addWidget(self.saveButtonSingle)
        self.ignoreButtonSingle = QtWidgets.QPushButton(self.tab)
        self.ignoreButtonSingle.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.ignoreButtonSingle.setFont(font)
        self.ignoreButtonSingle.setObjectName("ignoreButtonSingle")
        self.horizontalLayout_5.addWidget(self.ignoreButtonSingle)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 6, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.exitButtonAlbum = QtWidgets.QPushButton(self.tab_2)
        self.exitButtonAlbum.setMinimumSize(QtCore.QSize(131, 0))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.exitButtonAlbum.setFont(font)
        self.exitButtonAlbum.setObjectName("exitButtonAlbum")
        self.gridLayout_3.addWidget(self.exitButtonAlbum, 22, 4, 1, 1)
        self.findArtButtonAlbum = QtWidgets.QPushButton(self.tab_2)
        self.findArtButtonAlbum.setMinimumSize(QtCore.QSize(131, 0))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.findArtButtonAlbum.setFont(font)
        self.findArtButtonAlbum.setObjectName("findArtButtonAlbum")
        self.gridLayout_3.addWidget(self.findArtButtonAlbum, 18, 4, 1, 1)
        self.destntryAlbum = QtWidgets.QLineEdit(self.tab_2)
        self.destntryAlbum.setMinimumSize(QtCore.QSize(281, 0))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setUnderline(False)
        self.destntryAlbum.setFont(font)
        self.destntryAlbum.setObjectName("destntryAlbum")
        self.gridLayout_3.addWidget(self.destntryAlbum, 12, 3, 1, 2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_8.addWidget(self.label_26)
        self.diskNumSpinAlbum = QtWidgets.QSpinBox(self.tab_2)
        self.diskNumSpinAlbum.setMaximum(3000)
        self.diskNumSpinAlbum.setProperty("value", 1)
        self.diskNumSpinAlbum.setObjectName("diskNumSpinAlbum")
        self.horizontalLayout_8.addWidget(self.diskNumSpinAlbum)
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_8.addWidget(self.label_27)
        self.totalDiskSpinAlbum = QtWidgets.QSpinBox(self.tab_2)
        self.totalDiskSpinAlbum.setMaximum(3000)
        self.totalDiskSpinAlbum.setProperty("value", 2)
        self.totalDiskSpinAlbum.setObjectName("totalDiskSpinAlbum")
        self.horizontalLayout_8.addWidget(self.totalDiskSpinAlbum)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 22, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.GenreEntryAlbum = QtWidgets.QLineEdit(self.tab_2)
        self.GenreEntryAlbum.setMinimumSize(QtCore.QSize(371, 0))
        self.GenreEntryAlbum.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setUnderline(False)
        self.GenreEntryAlbum.setFont(font)
        self.GenreEntryAlbum.setObjectName("GenreEntryAlbum")
        self.gridLayout_3.addWidget(self.GenreEntryAlbum, 9, 0, 2, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 4, 0, 1, 1)
        self.destuttonAlbum = QtWidgets.QPushButton(self.tab_2)
        self.destuttonAlbum.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(11)
        font.setUnderline(False)
        self.destuttonAlbum.setFont(font)
        self.destuttonAlbum.setObjectName("destuttonAlbum")
        self.gridLayout_3.addWidget(self.destuttonAlbum, 12, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 17, 0, 1, 1)
        self.composerEntryAlbum = QtWidgets.QLineEdit(self.tab_2)
        self.composerEntryAlbum.setMinimumSize(QtCore.QSize(371, 0))
        self.composerEntryAlbum.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setUnderline(False)
        self.composerEntryAlbum.setFont(font)
        self.composerEntryAlbum.setObjectName("composerEntryAlbum")
        self.gridLayout_3.addWidget(self.composerEntryAlbum, 12, 0, 1, 1)
        self.albumEntryAlbum = QtWidgets.QLineEdit(self.tab_2)
        self.albumEntryAlbum.setMinimumSize(QtCore.QSize(371, 0))
        self.albumEntryAlbum.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setUnderline(False)
        self.albumEntryAlbum.setFont(font)
        self.albumEntryAlbum.setObjectName("albumEntryAlbum")
        self.gridLayout_3.addWidget(self.albumEntryAlbum, 3, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setMaximumSize(QtCore.QSize(16777215, 5))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 13, 2, 3, 3)
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 13, 0, 2, 1)
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 0, 1, 24, 1)
        self.commentTextAlbum = QtWidgets.QTextEdit(self.tab_2)
        self.commentTextAlbum.setMinimumSize(QtCore.QSize(371, 70))
        self.commentTextAlbum.setMaximumSize(QtCore.QSize(500, 16777215))
        self.commentTextAlbum.setBaseSize(QtCore.QSize(371, 111))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setUnderline(False)
        self.commentTextAlbum.setFont(font)
        self.commentTextAlbum.setAcceptRichText(False)
        self.commentTextAlbum.setObjectName("commentTextAlbum")
        self.gridLayout_3.addWidget(self.commentTextAlbum, 18, 0, 2, 1)
        self.artistEntryAlbum = QtWidgets.QLineEdit(self.tab_2)
        self.artistEntryAlbum.setMinimumSize(QtCore.QSize(371, 0))
        self.artistEntryAlbum.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setUnderline(False)
        self.artistEntryAlbum.setFont(font)
        self.artistEntryAlbum.setObjectName("artistEntryAlbum")
        self.gridLayout_3.addWidget(self.artistEntryAlbum, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setMinimumSize(QtCore.QSize(60, 0))
        self.label_23.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_6.addWidget(self.label_23)
        self.yearSpinAlbum = QtWidgets.QSpinBox(self.tab_2)
        self.yearSpinAlbum.setMaximumSize(QtCore.QSize(150, 16777215))
        self.yearSpinAlbum.setMaximum(3000)
        self.yearSpinAlbum.setProperty("value", 2000)
        self.yearSpinAlbum.setObjectName("yearSpinAlbum")
        self.horizontalLayout_6.addWidget(self.yearSpinAlbum)
        spacerItem5 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 20, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 8, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 6, 0, 1, 1)
        self.saveButtonAlbum = QtWidgets.QPushButton(self.tab_2)
        self.saveButtonAlbum.setMinimumSize(QtCore.QSize(131, 0))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.saveButtonAlbum.setFont(font)
        self.saveButtonAlbum.setObjectName("saveButtonAlbum")
        self.gridLayout_3.addWidget(self.saveButtonAlbum, 19, 4, 1, 1)
        self.titleEditAlbum = QtWidgets.QLineEdit(self.tab_2)
        self.titleEditAlbum.setMinimumSize(QtCore.QSize(371, 0))
        self.titleEditAlbum.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setUnderline(False)
        self.titleEditAlbum.setFont(font)
        self.titleEditAlbum.setObjectName("titleEditAlbum")
        self.gridLayout_3.addWidget(self.titleEditAlbum, 1, 0, 1, 1)
        self.saveAllButtonAlbum = QtWidgets.QPushButton(self.tab_2)
        self.saveAllButtonAlbum.setMinimumSize(QtCore.QSize(131, 0))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.saveAllButtonAlbum.setFont(font)
        self.saveAllButtonAlbum.setObjectName("saveAllButtonAlbum")
        self.gridLayout_3.addWidget(self.saveAllButtonAlbum, 20, 4, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.addFileAlbum = QtWidgets.QPushButton(self.tab_2)
        self.addFileAlbum.setMinimumSize(QtCore.QSize(100, 0))
        self.addFileAlbum.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(11)
        font.setUnderline(False)
        self.addFileAlbum.setFont(font)
        self.addFileAlbum.setObjectName("addFileAlbum")
        self.horizontalLayout_9.addWidget(self.addFileAlbum)
        self.removeFileButtonAlbum = QtWidgets.QPushButton(self.tab_2)
        self.removeFileButtonAlbum.setMinimumSize(QtCore.QSize(100, 0))
        self.removeFileButtonAlbum.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(11)
        font.setUnderline(False)
        self.removeFileButtonAlbum.setFont(font)
        self.removeFileButtonAlbum.setObjectName("removeFileButtonAlbum")
        self.horizontalLayout_9.addWidget(self.removeFileButtonAlbum)
        self.removeAllAlbum = QtWidgets.QPushButton(self.tab_2)
        self.removeAllAlbum.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(11)
        font.setUnderline(False)
        self.removeAllAlbum.setFont(font)
        self.removeAllAlbum.setObjectName("removeAllAlbum")
        self.horizontalLayout_9.addWidget(self.removeAllAlbum)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 10, 2, 2, 2)
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 11, 0, 1, 1)
        self.contributorsEntryAlbum = QtWidgets.QLineEdit(self.tab_2)
        self.contributorsEntryAlbum.setMinimumSize(QtCore.QSize(371, 0))
        self.contributorsEntryAlbum.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setUnderline(False)
        self.contributorsEntryAlbum.setFont(font)
        self.contributorsEntryAlbum.setObjectName("contributorsEntryAlbum")
        self.gridLayout_3.addWidget(self.contributorsEntryAlbum, 7, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(220, 220))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.artLabelAlbum = QtWidgets.QLabel(self.groupBox_2)
        self.artLabelAlbum.setGeometry(QtCore.QRect(20, 20, 200, 200))
        self.artLabelAlbum.setFrameShape(QtWidgets.QFrame.Box)
        self.artLabelAlbum.setText("")
        self.artLabelAlbum.setObjectName("artLabelAlbum")
        self.gridLayout_3.addWidget(self.groupBox_2, 16, 2, 8, 2)
        self.tableWidgetAlbum = QtWidgets.QTableWidget(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(11)
        font.setUnderline(False)
        self.tableWidgetAlbum.setFont(font)
        self.tableWidgetAlbum.setAcceptDrops(True)
        self.tableWidgetAlbum.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.tableWidgetAlbum.setDefaultDropAction(QtCore.Qt.LinkAction)
        self.tableWidgetAlbum.setAlternatingRowColors(True)
        self.tableWidgetAlbum.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidgetAlbum.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetAlbum.setShowGrid(True)
        self.tableWidgetAlbum.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetAlbum.setWordWrap(False)
        self.tableWidgetAlbum.setObjectName("tableWidgetAlbum")
        self.tableWidgetAlbum.setColumnCount(2)
        self.tableWidgetAlbum.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAlbum.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAlbum.setHorizontalHeaderItem(1, item)
        self.tableWidgetAlbum.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetAlbum.horizontalHeader().setDefaultSectionSize(234)
        self.tableWidgetAlbum.horizontalHeader().setHighlightSections(False)
        self.tableWidgetAlbum.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidgetAlbum.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidgetAlbum.verticalHeader().setDefaultSectionSize(27)
        self.gridLayout_3.addWidget(self.tableWidgetAlbum, 0, 2, 10, 3)
        self.compilationEntryAlbum = QtWidgets.QLineEdit(self.tab_2)
        self.compilationEntryAlbum.setMinimumSize(QtCore.QSize(371, 0))
        self.compilationEntryAlbum.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setUnderline(False)
        self.compilationEntryAlbum.setFont(font)
        self.compilationEntryAlbum.setObjectName("compilationEntryAlbum")
        self.gridLayout_3.addWidget(self.compilationEntryAlbum, 15, 0, 2, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_7.addWidget(self.label_24)
        self.trackNumSpinAlbum = QtWidgets.QSpinBox(self.tab_2)
        self.trackNumSpinAlbum.setMaximum(3000)
        self.trackNumSpinAlbum.setProperty("value", 1)
        self.trackNumSpinAlbum.setObjectName("trackNumSpinAlbum")
        self.horizontalLayout_7.addWidget(self.trackNumSpinAlbum)
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_7.addWidget(self.label_25)
        self.totalTracksAlbum = QtWidgets.QSpinBox(self.tab_2)
        self.totalTracksAlbum.setMaximum(3000)
        self.totalTracksAlbum.setProperty("value", 10)
        self.totalTracksAlbum.setObjectName("totalTracksAlbum")
        self.horizontalLayout_7.addWidget(self.totalTracksAlbum)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 21, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 891, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Title:"))
        self.label_2.setText(_translate("MainWindow", "Album :"))
        self.label_4.setText(_translate("MainWindow", "Album Artist:"))
        self.label_3.setText(_translate("MainWindow", "Contributing Artist(s): "))
        self.label_5.setText(_translate("MainWindow", "Genre:"))
        self.label_6.setText(_translate("MainWindow", "Composer: "))
        self.label_7.setText(_translate("MainWindow", "Compilation: "))
        self.label_8.setText(_translate("MainWindow", "Comment : "))
        self.label_9.setText(_translate("MainWindow", "Year :"))
        self.label_10.setText(_translate("MainWindow", "Track Number:"))
        self.label_11.setText(_translate("MainWindow", "of"))
        self.label_13.setText(_translate("MainWindow", "Disc Number: "))
        self.label_12.setText(_translate("MainWindow", "of"))
        self.groupBox.setTitle(_translate("MainWindow", "Song Art:"))
        self.artLabelSingle.setToolTip(_translate("MainWindow", "No image..."))
        self.findArtButtonSingle.setText(_translate("MainWindow", "Find New"))
        self.label_14.setText(_translate("MainWindow", "Path:"))
        self.openButtonSingle.setText(_translate("MainWindow", "Open"))
        self.saveButtonSingle.setText(_translate("MainWindow", "Save!"))
        self.ignoreButtonSingle.setText(_translate("MainWindow", "Ignore"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Edit Single File MetaData"))
        self.exitButtonAlbum.setText(_translate("MainWindow", "Exit"))
        self.findArtButtonAlbum.setText(_translate("MainWindow", "Find Art"))
        self.destntryAlbum.setToolTip(_translate("MainWindow", "This Destination Is only used when <Save Album> is called"))
        self.destntryAlbum.setPlaceholderText(_translate("MainWindow", "Destination Path For Your Album"))
        self.label_26.setText(_translate("MainWindow", "Disc Number: "))
        self.label_27.setText(_translate("MainWindow", "of"))
        self.label_15.setText(_translate("MainWindow", "Title:"))
        self.label_17.setText(_translate("MainWindow", "Album Artist:"))
        self.destuttonAlbum.setText(_translate("MainWindow", "Destnation"))
        self.label_22.setText(_translate("MainWindow", "Comment : "))
        self.label_21.setText(_translate("MainWindow", "Compilation: "))
        self.label_23.setText(_translate("MainWindow", "Year :"))
        self.label_19.setText(_translate("MainWindow", "Genre:"))
        self.label_16.setText(_translate("MainWindow", "Album :"))
        self.label_18.setText(_translate("MainWindow", "Contributing Artist(s): "))
        self.saveButtonAlbum.setText(_translate("MainWindow", "Save Album"))
        self.saveAllButtonAlbum.setText(_translate("MainWindow", "Save All"))
        self.addFileAlbum.setText(_translate("MainWindow", "Add File"))
        self.removeFileButtonAlbum.setText(_translate("MainWindow", "Remove File"))
        self.removeAllAlbum.setText(_translate("MainWindow", "Remove All"))
        self.label_20.setText(_translate("MainWindow", "Composer: "))
        self.groupBox_2.setTitle(_translate("MainWindow", "Album Art:"))
        self.artLabelAlbum.setToolTip(_translate("MainWindow", "No Image"))
        self.tableWidgetAlbum.setSortingEnabled(True)
        item = self.tableWidgetAlbum.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidgetAlbum.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Path"))
        self.label_24.setText(_translate("MainWindow", "Track Number:"))
        self.label_25.setText(_translate("MainWindow", "of"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Create An Album"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
